'use client'
import { useEffect, useMemo, useState } from 'react'
import { money, ym } from '@/lib/money'
import TopBar from '@/components/TopBar'

type Expense={expense_date:string,category:string,vendor_name:string,amount:number,payment_mode:string,description:string,bill_url:string}
type Summary={month:string,start_date?:string,has_data?:boolean,message?:string,opening_balance:number,maintenance_collected:number,other_income:number,total_expenses:number,closing_balance:number,expenses:Expense[],trend:{month:string,total_expenses:number}[]}
function pct(v:number,total:number){return total?Math.round((v/total)*100):0}
function shortMonth(m:string){const [y,mo]=m.split('-').map(Number); return new Date(y,mo-1,1).toLocaleString('en-IN',{month:'short'})}
export default function Resident(){
 const [logged,setLogged]=useState(false), [err,setErr]=useState(''), [month,setMonth]=useState(ym()), [summary,setSummary]=useState<Summary|null>(null)
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); setErr(''); const fd=new FormData(e.currentTarget); const r=await fetch('/api/resident/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(fd.entries()))}); if(r.ok){setLogged(true); load()} else setErr('Invalid flat number or PIN')}
 async function load(){const r=await fetch(`/api/resident/summary?month=${month}`); if(r.ok){setLogged(true); setSummary(await r.json())}}
 useEffect(()=>{load()},[month])
 const categories=useMemo(()=>{const map:Record<string,number>={}; (summary?.expenses||[]).forEach(x=>map[x.category]=(map[x.category]||0)+Number(x.amount)); return Object.entries(map).sort((a,b)=>b[1]-a[1])},[summary])
 const top=useMemo(()=>[...(summary?.expenses||[])].sort((a,b)=>Number(b.amount)-Number(a.amount)).slice(0,5),[summary])
 const maxTrend=Math.max(...(summary?.trend||[]).map(x=>x.total_expenses),1)
 if(!logged) return <><TopBar/><main className="wrap"><div className="card login-card"><h1>Sampada Residency Financials</h1><p className="muted">Enter your Flat No and PIN to see monthly expenses and balances. No personal details are required.</p><form onSubmit={login} className="grid"><label>Flat No</label><input name="flat_no" placeholder="A-204" required/><label>PIN</label><input name="pin" type="password" inputMode="numeric" placeholder="PIN" required/><button className="btn">View Statement</button>{err&&<p style={{color:'crimson'}}>{err}</p>}</form></div></main></>
 return <><TopBar/><main className="wrap"><div className="header"><div><h1>Monthly Statement</h1><p className="muted">View-only association financial summary.</p></div><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div>{summary?.has_data===false&&<div className="card"><h2>No data for this month</h2><p className="muted">{summary.message || 'No records are available for the selected month.'}</p><p>Please select a month from {summary.start_date?.slice(0,7) || 'the start month'} onwards.</p></div>}{summary&&summary.has_data!==false&&<>
 <div className="card"><h2>Financial Summary</h2><div className="grid2"><div className="stat blue"><span>Opening Balance</span><br/><b>{money(summary.opening_balance)}</b></div><div className="stat green"><span>Maintenance Collected</span><br/><b>{money(summary.maintenance_collected)}</b></div><div className="stat purple"><span>Other Income</span><br/><b>{money(summary.other_income)}</b></div><div className="stat orange"><span>Total Expenses</span><br/><b>{money(summary.total_expenses)}</b></div></div><div className="flow"><span>{money(summary.opening_balance)}</span><b>+</b><span>{money(summary.maintenance_collected+summary.other_income)}</span><b>-</b><span>{money(summary.total_expenses)}</span><b>=</b><strong>{money(summary.closing_balance)}</strong></div><div className="closing">Closing Balance: <b>{money(summary.closing_balance)}</b></div></div>
 <div className="card"><h2>Where Maintenance Money Went</h2><div className="chart-row"><div className="donut"><div>{pct(summary.total_expenses,summary.maintenance_collected+summary.other_income)}%<small>spent</small></div></div><div className="bars">{categories.map(([cat,amt])=><div key={cat} className="bar-line"><div><b>{cat}</b><span>{money(amt)}</span></div><div className="bar"><i style={{width:`${pct(amt,summary.total_expenses)}%`}}/></div></div>)}</div></div></div>
 <div className="card"><h2>Monthly Expense Trend</h2><div className="trend">{(summary.trend||[]).map(t=><div key={t.month} className="trend-item"><div className="trend-bar" style={{height:`${Math.max(8,(t.total_expenses/maxTrend)*120)}px`}}/><span>{shortMonth(t.month)}</span><small>{money(t.total_expenses)}</small></div>)}</div></div>
 <div className="card"><h2>Top Expenses This Month</h2>{top.map((x,i)=><div className="list-item" key={i}><span>{i+1}. {x.category}<small>{x.description||x.vendor_name}</small></span><b>{money(Number(x.amount))}</b></div>)}</div>
 <div className="card"><h2>Expense List</h2><table className="table compact-expense-table"><thead><tr><th>Date</th><th>Category</th><th>Amount</th></tr></thead><tbody>{summary.expenses.map((x,i)=><tr key={i}><td>{x.expense_date}</td><td>{x.category}</td><td>{money(Number(x.amount))}</td></tr>)}</tbody></table></div><div className="footer-note">© 2026 Sampada Residency, Bangalore. Made with 💚 for our community</div></>}</main></>
}
