'use client'
import { useState } from 'react'
import * as XLSX from 'xlsx'
function normalizeRow(row:any){const out:any={}; Object.keys(row).forEach(k=>{out[String(k).trim()]=row[k]}); return out}
export default function ImportPage(){
 const [type,setType]=useState<'expenses'|'collections'>('expenses'); const [rows,setRows]=useState<any[]>([]); const [msg,setMsg]=useState('')
 async function pick(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0]; if(!file) return; const data=await file.arrayBuffer(); const wb=XLSX.read(data,{cellDates:true}); const ws=wb.Sheets[wb.SheetNames[0]]; const json=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false,dateNF:'yyyy-mm-dd'}).map(normalizeRow); setRows(json.slice(0,5000)); setMsg(`${json.length} rows loaded. Review first rows below.`)}
 async function upload(){setMsg('Importing...'); const r=await fetch('/api/admin/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,rows})}); const j=await r.json(); setMsg(r.ok?`Imported ${j.imported} rows successfully.`:(j.error||'Import failed'))}
 const expenseCols='Expense Date / Date, Expense Category / Category, Expense Description / Description, Expense Amount / Amount'; const collectionCols='Month (YYYY-MM), Opening Balance, Maintenance Collected, Other Income, Notes'
 return <main className="wrap"><div className="header"><div><h1>Import Excel</h1><p className="muted">Upload your existing Excel file and push old data into Supabase.</p></div><a className="btn secondary" href="/admin">Back</a></div><div className="card grid"><label>Import type</label><select value={type} onChange={e=>{setType(e.target.value as any);setRows([])}}><option value="expenses">Detailed expenses</option><option value="collections">Monthly maintenance collection</option></select><p className="muted"><b>Expected columns:</b> {type==='expenses'?expenseCols:collectionCols}</p><input type="file" accept=".xlsx,.xls,.csv" onChange={pick}/>{rows.length>0&&<button className="btn" onClick={upload}>Import {rows.length} rows</button>}<p className="muted">{msg}</p></div>{rows.length>0&&<div className="card"><h2>Preview</h2><table className="table"><thead><tr>{Object.keys(rows[0]||{}).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,10).map((r,i)=><tr key={i}>{Object.keys(rows[0]||{}).map(k=><td key={k}>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div>}</main>
}
