'use client';import {useEffect,useMemo,useState} from 'react';import Link from 'next/link';import {money} from '@/lib/money';
export default function AdminGanesh(){
 const [data,setData]=useState<any>({donations:[],games:[],registrations:[],expenses:[],prasadam:[]}),[msg,setMsg]=useState(''),[editingGame,setEditingGame]=useState<any>(null);
 async function load(){const r=await fetch('/api/admin/ganesh');if(r.ok)setData(await r.json())}
 useEffect(()=>{load()},[]);
 async function post(body:any){setMsg('Saving...');const r=await fetch('/api/admin/ganesh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setMsg(r.ok?'Saved':'Could not save');await load();return r.ok}
 async function remove(action:string,id:any,label:string){if(!window.confirm(`Delete this ${label}? This cannot be undone.`))return;await post({action,id})}
 async function game(e:any){e.preventDefault();const form=e.currentTarget as HTMLFormElement;const f=Object.fromEntries(new FormData(form).entries());const ok=await post({action:'game',...f});if(ok)form.reset()}
 async function updateGame(e:any){e.preventDefault();const form=e.currentTarget as HTMLFormElement;const f=Object.fromEntries(new FormData(form).entries());const ok=await post({action:'game-update',id:editingGame.id,...f});if(ok)setEditingGame(null)}
 async function deleteGame(g:any){const count=data.registrations.filter((x:any)=>x.game_id===g.id).length;const warning=count?`Delete ${g.name}? This will also delete ${count} registration${count===1?'':'s'} for this game.`:`Delete ${g.name}?`;if(!window.confirm(warning))return;const ok=await post({action:'game-delete',id:g.id});if(ok&&editingGame?.id===g.id)setEditingGame(null)}
 async function expense(e:any){e.preventDefault();const form=e.currentTarget as HTMLFormElement;const f=Object.fromEntries(new FormData(form).entries());const ok=await post({action:'expense',...f});if(ok)form.reset()}
 const confirmedDonationTotal=useMemo(()=>data.donations.filter((x:any)=>x.status==='paid').reduce((s:number,x:any)=>s+Number(x.amount||0),0),[data.donations]);
 const pendingDonationTotal=useMemo(()=>data.donations.filter((x:any)=>x.status==='pending').reduce((s:number,x:any)=>s+Number(x.amount||0),0),[data.donations]);
 const actionStyle={display:'flex',gap:8,flexWrap:'wrap' as const,justifyContent:'flex-end',flex:'0 0 auto'};
 const itemStyle={display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:12,alignItems:'center',padding:'14px',border:'1px solid #dbe5df',borderRadius:16,marginBottom:10,overflow:'hidden'};
 return <main className="wrap"><div className="header"><div><h1>Ganesh Chaturthi Admin</h1><p className="muted">Donations, games, expenses and prasadam.</p></div><Link className="btn secondary" href="/admin">Back</Link></div>{msg&&<p>{msg}</p>}
 <div className="card"><h2>Donations</h2><div className="grid2"><div className="stat green"><span>Total Confirmed Donations</span><br/><b>{money(confirmedDonationTotal)}</b></div><div className="stat orange"><span>Pending Confirmation</span><br/><b>{money(pendingDonationTotal)}</b></div></div><div style={{marginTop:16}}>{data.donations.length===0?<p className="muted">No donations submitted yet.</p>:<div>{data.donations.map((x:any)=><div key={x.id} style={{padding:'14px',border:'1px solid #dbe5df',borderRadius:16,marginBottom:10}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:12}}><div style={{minWidth:0}}><b style={{display:'block',fontSize:17}}>{x.donor_name}</b><small className="muted" style={{display:'block',marginTop:3}}>Flat {x.flat_no} · {x.created_at?new Date(x.created_at).toLocaleDateString('en-IN'):''}</small></div><b style={{fontSize:17,whiteSpace:'nowrap'}}>{money(Number(x.amount))}</b></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,marginTop:12,paddingTop:10,borderTop:'1px solid #edf1ee',flexWrap:'wrap'}}><span style={{fontWeight:700,color:x.status==='paid'?'#16743a':x.status==='pending'?'#9a6514':'#b4233f'}}>{x.status==='paid'?'✓ Paid':x.status==='pending'?'⏳ Pending':'Rejected'}</span><div style={actionStyle}>{x.status==='pending'&&<><button className="mini-btn" onClick={()=>post({action:'donation-status',id:x.id,status:'paid'})}>Mark Paid</button><button className="mini-btn danger" onClick={()=>post({action:'donation-status',id:x.id,status:'rejected'})}>Reject</button></>}<button className="mini-btn danger" onClick={()=>remove('donation-delete',x.id,'donation')}>Delete</button></div></div></div>)}</div>}</div></div>
 <div className="card"><h2>Add Game</h2><form className="grid" onSubmit={game}><input name="name" placeholder="Game name" required/><select name="category" defaultValue="All"><option>All</option><option>Men</option><option>Women</option><option>Kids</option></select><div className="grid2"><input name="event_date" type="date"/><input name="event_time" type="time"/></div><input name="max_participants" type="number" min="1" placeholder="Max participants (optional)"/><button className="btn">Add Game</button></form><h3>Games</h3>{data.games.length===0?<p className="muted">No games added yet.</p>:data.games.map((g:any)=><div style={itemStyle} key={g.id}><span style={{minWidth:0}}><b style={{display:'block',overflowWrap:'anywhere'}}>{g.name}</b><small className="muted" style={{display:'block',lineHeight:1.35}}>{g.category}{g.event_date?' · '+g.event_date:''}{g.event_time?' · '+String(g.event_time).slice(0,5):''}{g.max_participants?' · Max '+g.max_participants:''}</small></span><div style={actionStyle}><button className="mini-btn" onClick={()=>setEditingGame(g)}>Edit</button><button className="mini-btn danger" onClick={()=>deleteGame(g)}>Delete</button></div></div>)}{editingGame&&<div style={{marginTop:16,paddingTop:16,borderTop:'1px solid #ddd'}}><h3>Edit Game</h3><form className="grid" onSubmit={updateGame}><input name="name" defaultValue={editingGame.name} required/><select name="category" defaultValue={editingGame.category||'All'}><option>All</option><option>Men</option><option>Women</option><option>Kids</option></select><div className="grid2"><input name="event_date" type="date" defaultValue={editingGame.event_date||''}/><input name="event_time" type="time" defaultValue={editingGame.event_time?String(editingGame.event_time).slice(0,5):''}/></div><input name="max_participants" type="number" min="1" defaultValue={editingGame.max_participants||''} placeholder="Max participants (optional)"/><div className="row-actions"><button className="btn">Save Changes</button><button className="btn secondary" type="button" onClick={()=>setEditingGame(null)}>Cancel</button></div></form></div>}
 <h3>Registrations</h3>{data.registrations.length===0?<p className="muted">No registrations yet.</p>:data.registrations.map((x:any)=><div style={itemStyle} key={x.id}><span style={{minWidth:0}}>{x.ganesh_games?.name}<small className="muted" style={{display:'block'}}>{x.flat_no} · {x.participant_name}{x.age?' · Age '+x.age:''}</small></span><button className="mini-btn danger" onClick={()=>remove('registration-delete',x.id,'registration')}>Delete</button></div>)}</div>
 <div className="card"><h2>Add Event Expense</h2><form className="grid" onSubmit={expense}><input name="expense_date" type="date" required/><input name="category" placeholder="Category" required/><input name="description" placeholder="Short description"/><input name="amount" type="number" min="1" required/><input name="bill_url" placeholder="Bill URL (optional)"/><button className="btn">Add Expense</button></form><h3>Event Expenses</h3>{data.expenses.length===0?<p className="muted">No event expenses added yet.</p>:data.expenses.map((x:any)=><div style={itemStyle} key={x.id}><span style={{minWidth:0}}><b>{x.category}</b><small className="muted" style={{display:'block'}}>{x.expense_date}{x.description?' · '+x.description:''}</small></span><div style={actionStyle}><b>{money(Number(x.amount))}</b><button className="mini-btn danger" onClick={()=>remove('expense-delete',x.id,'expense')}>Delete</button></div></div>)}</div>
 <div className="card"><h2>Prasadam Donations</h2>{data.prasadam.length===0?<p className="muted">No prasadam donations yet.</p>:data.prasadam.map((x:any)=><div style={itemStyle} key={x.id}><span style={{minWidth:0}}><b>{x.event_date} · {x.slot}</b><small className="muted" style={{display:'block'}}>{x.flat_no} · {x.donor_name} · {x.prasadam}</small></span><button className="mini-btn danger" onClick={()=>remove('prasadam-delete',x.id,'prasadam entry')}>Delete</button></div>)}</div>
 </main>}
