create table if not exists public.resident_report_access (
  id bigint generated by default as identity primary key,
  flat_no text not null,
  viewed_at timestamptz not null default now()
);

create index if not exists resident_report_access_flat_no_idx
  on public.resident_report_access (flat_no);

create index if not exists resident_report_access_viewed_at_idx
  on public.resident_report_access (viewed_at desc);
