-- Manual collections table. Safe to run on a new or existing database.
create table if not exists public.monthly_income (
  id bigint generated by default as identity primary key,
  month text not null,
  income_type text not null,
  amount numeric(12,2) not null check (amount >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.monthly_income add column if not exists month text;
alter table public.monthly_income add column if not exists income_type text;
alter table public.monthly_income add column if not exists amount numeric(12,2);
alter table public.monthly_income add column if not exists notes text;
alter table public.monthly_income add column if not exists created_at timestamptz default now();
alter table public.monthly_income add column if not exists updated_at timestamptz default now();

create index if not exists monthly_income_month_idx on public.monthly_income(month);
