'use client'
import { useEffect, useState } from 'react'
import { money, ym } from '@/lib/money'

type Expense={id:string,expense_date:string,category:string,vendor_name:string,amount:number,payment_mode:string,paid_by:string,description:string,bill_url:string,status:string}
export default function Expenses(){
 const [month,setMonth]=useState(ym()); const [items,setItems]=useState<Expense[]>([]); const [msg,setMsg]=useState(''); const [balance,setBalance]=useState<any>(null)
 async function load(){const r=await fetch(`/api/admin/expenses?month=${month}`); const j=await r.json(); setItems(j.expenses||[]); const br=await fetch(`/api/admin/monthly-balance?month=${month}`); const bj=await br.json(); setBalance(bj.balance)}
 useEffect(()=>{load()},[month])
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); setMsg('Saving...'); const fd=new FormData(e.currentTarget); const body=Object.fromEntries(fd.entries()); const r=await fetch('/api/admin/expenses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); if(r.ok){setMsg('Expense saved'); e.currentTarget.reset(); load()} else setMsg('Could not save')}
 async function saveBalance(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); const fd=new FormData(e.currentTarget); const r=await fetch('/api/admin/monthly-balance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(fd.entries()))}); setMsg(r.ok?'Monthly balance saved':'Could not save balance'); load()}
 const total=items.reduce((s,x)=>s+Number(x.amount),0)
 const csv='Date,Category,Vendor,Amount,Payment Mode,Paid By,Description,Status\n'+items.map(x=>[x.expense_date,x.category,x.vendor_name,x.amount,x.payment_mode,x.paid_by,x.description,x.status].map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(',')).join('\n')
 return <main className="wrap"><div className="header"><div><h1>Expenses</h1><p className="muted">Mobile-friendly expense entry.</p></div><a className="btn secondary" href="/admin">Back</a></div><div className="card"><h2>Monthly Balance</h2><form onSubmit={saveBalance} className="grid"><input type="hidden" name="month" value={month}/><div className="grid2"><div><label>Opening Balance</label><input name="opening_balance" type="number" step="0.01" defaultValue={balance?.opening_balance||0}/></div><div><label>Maintenance Collected</label><input name="maintenance_collected" type="number" step="0.01" defaultValue={balance?.maintenance_collected||0}/></div></div><div className="grid2"><div><label>Other Income</label><input name="other_income" type="number" step="0.01" defaultValue={balance?.other_income||0}/></div><div><label>Notes</label><input name="notes" defaultValue={balance?.notes||''}/></div></div><button className="btn secondary">Save Monthly Balance</button></form></div><div className="card"><h2>Add Expense</h2><form onSubmit={submit} className="grid"><div className="grid2"><div><label>Date</label><input name="expense_date" type="date" required/></div><div><label>Amount</label><input name="amount" type="number" min="0" step="0.01" required/></div></div><div className="grid2"><div><label>Category</label><select name="category" required><option>Security</option><option>Cleaning</option><option>Electricity</option><option>Water</option><option>Repairs</option><option>Lift</option><option>Common Area</option><option>Other</option></select></div><div><label>Payment Mode</label><select name="payment_mode"><option>UPI</option><option>Bank Transfer</option><option>Cash</option><option>Cheque</option></select></div></div><div className="grid2"><div><label>Vendor Name</label><input name="vendor_name" placeholder="Vendor / shop name"/></div><div><label>Paid By</label><input name="paid_by" placeholder="Treasurer / committee member"/></div></div><label>Description</label><textarea name="description" placeholder="Short note"></textarea><label>Bill URL</label><input name="bill_url" placeholder="Paste Google Drive / invoice link for now"/><button className="btn">Save Expense</button><p className="muted">{msg}</p></form></div><div className="card"><div className="header"><div><h2>Monthly Expenses</h2><p><b>Total:</b> {money(total)}</p></div><div className="mobile-actions"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><a className="btn secondary" download={`expenses-${month}.csv`} href={`data:text/csv;charset=utf-8,${encodeURIComponent(csv)}`}>Download CSV</a></div></div><table className="table"><thead><tr><th>Date</th><th>Category</th><th>Vendor</th><th>Amount</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.expense_date}</td><td>{x.category}</td><td>{x.vendor_name}</td><td>{money(Number(x.amount))}</td></tr>)}</tbody></table></div></main>
}
